### ISSUE TITLE
Plugin no longer supported.

### ISSUE THREAD

**Issue by amalija-kihtten** [AlexCSDev/XIVWindowResizer#4]
As of the latest update, this plugin is no longer supported. 
If possible, can you update this plugin?
Thank you for your time and effort.

**Comment by AlexCSDev** [comment]
Yes, this plugin will be updated once I get back from my vacation. Probably some time next week.

**Comment by amalija-kihtten** [comment]
oooh, than enjoy your vacation, sorry for bothering <3

**Comment by AlexCSDev** [comment]
Sent update to dalamud team for approval

**Comment by amalija-kihtten** [comment]
Thank you soo much <3
