### ISSUE TITLE
Not working on the current version anymore?

### ISSUE THREAD

**Issue by salmoooon** [AlexCSDev/XIVWindowResizer#6]
After adding the custom repo, the plugin isn't showing in the available plugin list, and installing it manually as a dev plugin throws an error. Is anyone else having this issue?

**Comment by Wapi35** [comment]
Yea Im also having the same issue with the plugin and have no idea how to get it to show in the plugin list.

**Comment by RisaDev** [comment]
Enable testing plugins in dalamud settings and get the plugin from official dalamud repository.
