### ISSUE TITLE
Resizing from 1080 to 4k clips past monitor.

### ISSUE THREAD

**Issue by Dark-Cr0w** [AlexCSDev/XIVWindowResizer#9]
Not entirely sure how to explain but this is a screenshot of my _entire screen_ when i set the resolution to 4k.
I have a 1080 monitor but I trying to take 4k screenshots. Screen mode is Borderless Windowed, if that helps.

![image](https://github.com/user-attachments/assets/41091b39-0b26-4709-8ae7-92689f704562)

**Comment by AlexCSDev** [comment]
This is expected behavior for borderless windowed mode.
